# Generated by Django 5.1.5 on 2025-02-03 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32)),
                ('nbre_bloc', models.IntegerField(verbose_name='Nombre bloc')),
            ],
            options={
                'verbose_name_plural': 'Batiments',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=10)),
                ('nbre_place', models.IntegerField(verbose_name='Nombre Place')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('libelle', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Matieres',
            },
        ),
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Blocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32)),
                ('nbre_salle', models.IntegerField(verbose_name='Nombre Salle')),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.batiments')),
            ],
            options={
                'verbose_name_plural': 'Blocs',
            },
        ),
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('matricule', models.CharField(editable=False, max_length=4)),
                ('prenom', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='image')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10)),
                ('datenaissance', models.DateField(verbose_name='Date de naissance')),
                ('lieunaissance', models.CharField(max_length=50, verbose_name='Lieu de naissance')),
                ('pere', models.CharField(max_length=50)),
                ('mere', models.CharField(max_length=50)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecole.classes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eleves',
            },
        ),
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lu', 'Lundi'), ('Ma', 'Mardi'), ('Mr', 'Mercredi'), ('Je', 'Jeudi'), ('Ve', 'Vendredi'), ('Sa', 'Samedi')], max_length=10)),
                ('heuredebut', models.TimeField(verbose_name='Debut du cours')),
                ('heurefin', models.TimeField(verbose_name='Fin du cours')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.classes')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.cours')),
            ],
            options={
                'verbose_name_plural': 'Emplois',
            },
        ),
        migrations.CreateModel(
            name='EleveSeances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleves')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.emplois')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreEleve', models.IntegerField(verbose_name='Nombre Eleve')),
                ('date', models.DateField(verbose_name='Date')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.classes')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.cours')),
                ('eleve', models.ManyToManyField(to='ecole.eleves')),
            ],
            options={
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Inscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleves')),
            ],
            options={
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.matieres'),
        ),
        migrations.CreateModel(
            name='Mensualites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('mois', models.CharField(choices=[('Oct', 'Octobre'), ('Nov', 'Novembre'), ('Dec', 'Decembre'), ('Jan', 'Janvier'), ('Fev', 'Fevrier'), ('Mar', 'Mars'), ('Avr', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juil', 'Juillet')], max_length=20)),
                ('moyenpai', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleves')),
            ],
            options={
                'verbose_name_plural': 'Mensualites',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.niveaux'),
        ),
        migrations.AddField(
            model_name='classes',
            name='niveaux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.niveaux'),
        ),
        migrations.AddField(
            model_name='niveaux',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.options'),
        ),
        migrations.AddField(
            model_name='cours',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.options'),
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Ins', 'Inscription'), ('Reins', 'Reinscription'), ('Mens', 'Mensualite')], max_length=20)),
                ('montant', models.FloatField()),
                ('modepaie', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleves')),
            ],
            options={
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Profs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.BigIntegerField(verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profs',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.FloatField()),
                ('note2', models.FloatField()),
                ('note3', models.FloatField()),
                ('moy', models.FloatField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.eleves')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.evaluations')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecole.profs')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.AddField(
            model_name='emplois',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.profs'),
        ),
        migrations.AddField(
            model_name='cours',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.profs'),
        ),
        migrations.CreateModel(
            name='Salles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=32)),
                ('nbr_place', models.IntegerField(verbose_name='Nombre place')),
                ('disponibilite', models.BooleanField()),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.blocs')),
            ],
            options={
                'verbose_name_plural': 'salles',
            },
        ),
        migrations.AddField(
            model_name='emplois',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.salles'),
        ),
        migrations.CreateModel(
            name='Seances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heuredebut', models.TimeField(verbose_name='Debut du cours')),
                ('heurefin', models.TimeField(verbose_name='Fin du cours')),
                ('nombreEleve', models.IntegerField(verbose_name='Nombre eleve')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.classes')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.cours')),
                ('eleve', models.ManyToManyField(through='ecole.EleveSeances', to='ecole.eleves')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.profs')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.salles')),
            ],
            options={
                'verbose_name_plural': 'Seances',
            },
        ),
        migrations.AddField(
            model_name='eleveseances',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecole.seances'),
        ),
        migrations.CreateModel(
            name='Tuteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('tel', models.BigIntegerField(verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tuteurs',
            },
        ),
        migrations.AddField(
            model_name='eleves',
            name='tuteurs',
            field=models.ManyToManyField(to='ecole.tuteurs'),
        ),
    ]
