# Generated by Django 5.1.5 on 2025-02-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
    ]
