# Generated by Django 5.1.5 on 2025-02-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_alter_classes_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleves',
            name='sexe',
            field=models.CharField(max_length=10),
        ),
    ]
