# Generated by Django 5.1.5 on 2025-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0004_alter_eleves_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='moy',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='eleves',
            name='tuteurs',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note1',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note2',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note3',
        ),
        migrations.AddField(
            model_name='tuteurs',
            name='enfant',
            field=models.ManyToManyField(to='ecole.eleves'),
        ),
    ]
